# GoReleaser configuration (v1 compatible)
version: 1

project_name: try

before:
  hooks:
    - go mod tidy

builds:
  - id: try
    main: ./cmd/try
    binary: try
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/amulcse/try/internal/config.Version={{.Version}}
      - -X github.com/amulcse/try/internal/config.BuildTime={{.Date}}

archives:
  - id: default
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "Merge pull request"
      - "Merge branch"

release:
  github:
    owner: amulcse
    name: try
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
  header: |
    ## try v{{.Version}}
    
    A Go port of [tobi/try](https://github.com/tobi/try) - fresh directories for every vibe 🏠
    
    ### Installation
    
    ```bash
    # macOS (Apple Silicon)
    curl -LO https://github.com/amulcse/try/releases/latest/download/try_darwin_arm64.tar.gz
    tar -xzf try_darwin_arm64.tar.gz && sudo mv try /usr/local/bin/
    
    # Or use Go
    go install github.com/amulcse/try/cmd/try@latest
    ```
  footer: |
    ---
    All credit for the original idea goes to [Tobi Lütke](https://github.com/tobi) and [try](https://github.com/tobi/try).

brews:
  - name: try
    repository:
      owner: amulcse
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/amulcse/try"
    description: "Fresh directories for every vibe - ephemeral workspace manager"
    license: "MIT"
    directory: Formula
    install: |
      bin.install "try"
    caveats: |
      To complete installation, add this to your shell config:

      For bash/zsh (~/.bashrc or ~/.zshrc):
        eval "$(try init)"

      For fish (~/.config/fish/config.fish):
        eval (try init | string collect)

      Then restart your terminal.
    test: |
      system "#{bin}/try", "--version"
